imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        save_path: %kernel.root_dir%/var/sessions
    fragments:       ~
    http_method_override: true
    
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [FMElfinderBundle]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false
        
# Swiftmailer Configuration
swiftmailer:
    transport:      %mailer_transport%
    host:           %mailer_host%
    username:       %mailer_user%
    password:       %mailer_password%
    port:           %mailer_port%
    encryption:     %mailer_encryption%
    #spool:     { type: memory }
    
# StofDOctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    default_locale: %locale%

    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path:       %kernel.root_dir%/../web/uploads
        # Mime type guesser class: Optional. By default, we provide an adapter for the one present in the HttpFoundation component of Symfony
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        # Default file info class implementing FileInfoInterface: Optional. By default we provide a class which is prepared to receive an UploadedFile instance.
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:  
        default:
            uploadable: true
            translatable: true
            sluggable: true
    mongodb: ~
    
# A2lixTranslationFormBundle Configuration
a2lix_translation_form:
    locales: %locales%

# FOSUserBundle Configuration    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: LittleBigJoe\Bundle\CoreBundle\Entity\User
    registration:
        form:
            type: littlebigjoe_bundle_frontendbundle_user_registration_beta
    profile:
        form:
            type: littlebigjoe_bundle_frontendbundle_user_profile

# FOSFacebookBundle Configuration
fos_facebook:
    alias:  facebook
    app_id: %api_facebook_id%
    secret: %api_facebook_secret%
    cookie: true
    permissions: [email, publish_stream, user_about_me, user_birthday, user_location, user_website]

# HWIOAuthBundle Configuration
hwi_oauth:
    connect:
        account_connector: littlebigjoefrontend.fos_ub_user_provider
    firewall_name: main
    fosub:
        username_iterations: 30
        properties:
            twitter: twitterId
    resource_owners: 
        twitter:
            type: twitter
            client_id: "%api_twitter_key%"
            client_secret: "%api_twitter_secret%"
              
# KNPPaginatorBundle Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: LittleBigJoeBackendBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

# KNPMenuBundle Configuration
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig

# JMSI18NRoutingBundle Configuration
jms_i18n_routing:
    default_locale: %locale%
    locales: %locales%
    strategy: prefix

# JMSTranslationBundle Configuration
jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: []
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs]
            output_format: xliff

# JMSTranslationBundle Configuration   
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
    
# TrsteelCkeditorBundle Configuration
trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\Type\CkeditorType
    transformers: ['strip_js', 'strip_css', 'strip_comments']
    ui_color: '#FFFFFF'
    startup_outline_blocks: false
    width: 800 #Integer or %
    height: 300 #Integer or %    
    language: 'en-US'
    # Used to avoid some problems regarding iframes/embed placeholders (check template override in /app folder)
    custom_config: "toolbar: [{ name: 'clipboard', groups: [ 'clipboard', 'undo' ], items: [ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord' ] }, { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ], items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] }, { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] }, { name: 'insert', items: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] }, '/', { name: 'document', items: [ 'Source' ]}, { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] }]"
    external_plugins:
        oembed:
            path: js/ckeditor/plugins/oembed
    filebrowser_image_browse_url:
        route: elfinder

# FMElfinderBundle Configuration
fm_elfinder:
    locale: %locale%
    editor: ckeditor # other choices are tinymce or simple
    connector:
        debug: false # defaults to false
        roots:       # at least one root must be defined
            uploads:
                driver: LocalFileSystem
                path: uploads/tmp/user
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                upload_deny: ['all']
                upload_max_size: 10M

# KNPTimeBundle Configuration
knp_time: ~

# AvalancheImagineBundle Configuration
avalanche_imagine:
    filters:
        780x495:
            type:    thumbnail
            options: { size: [780, 495], mode: inset, quality: 100, format: jpeg }
        750x500:
            type:    thumbnail
            options: { size: [750, 500], mode: inset, quality: 95, format: jpeg }
        722x445:
            type:    thumbnail
            options: { size: [722, 445], mode: inset, quality: 95, format: jpeg }
        690x690:
            type:    thumbnail
            options: { size: [690, 690], mode: inset, quality: 95, format: jpeg }
        690x500:
            type:    thumbnail
            options: { size: [690, 500], mode: inset, quality: 95, format: jpeg }
        690x460:
            type:    thumbnail
            options: { size: [690, 460], mode: inset, quality: 95, format: png }
        581x581:
            type:    thumbnail
            options: { size: [581, 581], mode: inset, quality: 95, format: jpeg }
        534x329:
            type:    thumbnail
            options: { size: [534, 329], mode: outbound, quality: 95, format: jpeg }
        346x215:
            type:    thumbnail
            options: { size: [346, 215], mode: outbound, quality: 95, format: jpeg }
        260x174:
            type:    thumbnail
            options: { size: [260, 174], mode: outbound, quality: 95, format: jpeg }
        255x255:
            type:    thumbnail
            options: { size: [255, 255], mode: inset, quality: 95, format: png }
        230x268:
            type:    thumbnail
            options: { size: [230, 268], mode: inset, quality: 95, format: jpeg }
        239x239:
            type:    thumbnail
            options: { size: [239, 239], mode: inset, quality: 95, format: jpeg }


# LittleBigJoeBundle Configuration
little_big_joe_mango_pay: 
    leetchi_base_url: '%leetchi_base_url_prod%'
    leetchi_private_key_file: '%kernel.root_dir%/../%leetchi_private_key_file_name%'