# FOSUserBundle routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    options: { i18n: false }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    options: { i18n: false }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# FOSFacebookBundle routing
_security_check:
    pattern:  /login_facebook_check
    options: { i18n: false }
    
_security_logout:
    pattern:  /logout
    options: { i18n: false }

# HWIOAuthBundle routing
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login
    options: { i18n: false }
 
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
    options: { i18n: false }
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /login
    options: { i18n: false }

twitter_login:
    pattern: /login/check-twitter
    options: { i18n: false }
 
# FMElfinderBundle routing
elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
    options: { i18n: false }
 
# LittleBigJoe routing
little_big_joe_frontend:
    resource: "@LittleBigJoeFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

little_big_joe_backend:
    resource: "@LittleBigJoeBackendBundle/Controller/"
    type:     annotation
    prefix:   /admin/
    defaults:  { _locale: fr } # Force the locale, to show admin in French
    options: { i18n: false }