security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_BETA_USER:   ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_BRAND_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        littlebigjoe_facebook_provider:
            id: littlebigjoefrontend.user.facebook_provider
        chain_provider:
            chain:
                providers: [fos_userbundle, littlebigjoe_facebook_provider]    
                
    firewalls:
        main:        
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            
            fos_facebook:
                app_url: "%api_facebook_name%"
                server_url: "%api_facebook_server%"
                check_path: /login_facebook_check   # Avoid problem with base form
                provider: littlebigjoe_facebook_provider
            
            oauth:
                resource_owners:
                    twitter: "/login/check-twitter"
                login_path: /register
                failure_path: /register
 
                oauth_user_provider:
                    service: littlebigjoefrontend.fos_ub_user_provider
            
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt , role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/beta, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }
        - { path: ^/, role: ROLE_BETA_USER }


