<?php

namespace LittleBigJoe\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends EntityRepository
{
    public function findAllByCategory()
    {
        return $this->createQueryBuilder('f')
                ->leftJoin('f.category', 'fc')
                ->where('f.isVisible = :isVisible')
                ->setParameter('isVisible', true)
                ->orderBy('fc.name', 'ASC')
                ->getQuery()
                ->getResult();

    }
}
