<?php

namespace LittleBigJoe\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    /**
     * Return the number of unread notifications
     *
     * @param integer/null $userId : user id
     * @return int totalUnreadNotifications
     */
    public function getUnreadNotifications($userId)
    {
        return $this->createQueryBuilder('n')
                    ->select('COUNT(n)')
                    ->where('n.viewed = :viewed')
                    ->andWhere('n.user = :user')
                    ->setParameters(array(
                        'viewed' => false,
                        'user' => $userId
                    ))
                    ->getQuery()
                    ->getSingleScalarResult();
    }
}
