<?php

namespace LittleBigJoe\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTypeRepository extends EntityRepository
{
    /**
     * Return product types similar to the serach
     *
     * @param string $term : Term to search in db
     * @param string $locale : Term language
     * @return array
     */
    public function findEquivalents($term, $locale)
    {
        $qb = $this->createQueryBuilder('pt')
            ->select('pt.name')
            ->where('pt.language = :language')
            ->andWhere('pt.isVisible = :isVisible')
            ->andWhere('LOWER(pt.name) LIKE :name')
            ->setParameters(array(
                'language' => $locale,
                'isVisible' => true,
                'name' => '%'.$term.'%'
            ));

        return $qb->getQuery()
            ->getResult();
    }
}
