<?php

namespace LittleBigJoe\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WithdrawalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WithdrawalRepository extends EntityRepository
{
		/**
		 * Return the total of withdraws of projects
		 *
		 * @param integer/null $projectId :
		 *        if set to null, return the total of withdraws for all projects
		 *        if set to integer, return the total of withdraws for a specific project
		 * @return float totalWithdraw
		 */
		public function count($projectId = null)
		{
				$qb = $this->createQueryBuilder('w')
									 ->select('SUM(w.mangopayAmount)')
									 ->where('w.mangopayIsCompleted = :mangopayIsCompleted')
									 ->setParameter('mangopayIsCompleted', true)
									 ->andWhere('w.mangopayIsSucceeded = :mangopayIsSucceeded')
									 ->setParameter('mangopayIsSucceeded', true);		
		
				if (!empty($projectId)) {
						$qb = $qb->andWhere('w.project = :project')
										 ->setParameter('project', $projectId);
				}
		
				return $qb->getQuery()
									->getSingleScalarResult();
		}
}
