<?php

namespace LittleBigJoe\Bundle\FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends EntityRepository
{
    /**
     * Find by slug, indepently from the language
     *
     * @param string $slug : contains slug
     * @return object entity
     */
    public function findBySlugI18n($slug)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT f FROM LittleBigJoeFrontendBundle:Faq f WHERE f.slug LIKE :slug')
            ->setParameter('slug', '%' . $slug . '%')
            ->setHint(
                \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
                'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
            )
            ->getSingleResult();
    }
}
